[
    {
      "name": "CUSTNM",
      "value": "홍길동",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "CUSTNO",
      "value": "9510051111222",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTCNT",
      "value": "3",
      "type": "NUMBER",
      "action": "EQ",
      "valueType": "NUMBER"
    },
    {
      "name": "BANKCD1",
      "value": "003",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKNM1",
      "value": "국민은행",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTPK1",
      "value": "555555555",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTNO1",
      "value": "5709930987",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKCD2",
      "value": "003",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKNM2",
      "value": "국민은행2",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTPK2",
      "value": "555555555",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTNO2",
      "value": "57099309872",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKCD3",
      "value": "003",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKNM3",
      "value": "국민은행3",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTPK3",
      "value": "555555555",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTNO3",
      "value": "5709930983",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKCD4",
      "value": "003",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKNM4",
      "value": "국민은행4",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTPK4",
      "value": "555555555",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTNO4",
      "value": "5709930987",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKCD5",
      "value": "003",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "BANKNM5",
      "value": "국민은행5",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTPK5",
      "value": "555555555",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    },
    {
      "name": "ACNTNO5",
      "value": "5709930987",
      "type": "TEXT",
      "action": "EQ",
      "valueType": "TEXT"
    }
  ]